add CDP Selenium 4 support
AlexLAA/com.loliktest.ufit pull request #29
Opened 2022-02-18 13:25 UTC by IovetsNikolay

2022-02-22 08:39 UTC, petroOv-PDFfiller approved these changes

2022-02-23 12:11 UTC, dbudim requested changes

2022-02-23 12:11 UTC, dbudim commented on src/main/java/com/loliktest/ufit/DevTools.java
> +    public static org.openqa.selenium.devtools.DevTools getCdpDevTools(WebDriver chromeDriver) {
не совсем понимаю зачем метод, которому нужно еще и вебдрайвер передавать

2022-02-23 12:11 UTC, dbudim commented on src/main/java/com/loliktest/ufit/DevTools.java
> +    public static org.openqa.selenium.devtools.DevTools getCdpDevTools(WebDriver chromeDriver) {
идея ж в том чтобы ты работал с `browser() ` и он сам знал с каким ему драйвером работать

2022-02-23 12:11 UTC, dbudim commented on src/main/java/com/loliktest/ufit/DevTools.java
> +    public static org.openqa.selenium.devtools.DevTools getCdpDevTools(WebDriver chromeDriver) {
лучше чтобы просто был `getCdpDevTools()`

2022-02-23 12:11 UTC, dbudim commented on src/main/java/com/loliktest/ufit/DevTools.java
> +    public static NetworkUfit network(org.openqa.selenium.devtools.DevTools devTools) {
думаю это лишнее, противоречит идее ufit

2022-02-23 12:11 UTC, dbudim commented on src/main/java/com/loliktest/ufit/DevTools.java
> +    public static NetworkUfit network(org.openqa.selenium.devtools.DevTools devTools) {
то же самое ниже, думаю нам не надо метод куда надо еще передавать обьект дэвтулов. Если ты вызываешь network, то он должен сам понимать с чем ему работать

2022-02-23 12:11 UTC, dbudim commented on src/main/java/com/loliktest/ufit/chromeDevTools/NetworkUfit.java
> +    void enableModifyFetch(List<RequestPattern> requestPattern) {
почему package default модификатор?

2022-02-23 12:11 UTC, dbudim commented on src/main/java/com/loliktest/ufit/chromeDevTools/NetworkUfit.java
> +        devTools.send(Fetch.disable());
давай мб всетаки разнесем по разным доменам network и fetch?

2022-02-23 12:11 UTC, dbudim commented on src/main/java/com/loliktest/ufit/chromeDevTools/NetworkUfit.java
> +    org.openqa.selenium.devtools.DevTools devTools;
модификатор

2022-02-23 12:11 UTC, dbudim commented on src/main/java/com/loliktest/ufit/chromeDevTools/FetchUfit.java
> +            FetchUfit.this.url = url;
мб лучше класический билдер ?

2022-02-23 12:16 UTC, IovetsNikolay commented on src/main/java/com/loliktest/ufit/DevTools.java
> +    public static org.openqa.selenium.devtools.DevTools getCdpDevTools(WebDriver chromeDriver) {
Смысл как раз в использовании devTools без инициализации юфитовского класса браузер
В пуле селениума в классе [ChromeLocalBrowserConfig.java](https://github.com/airslateinc/qa-airslate-selenium/pull/2742/files#diff-86c166e24cac254828fd550eb1a32fc134aa927996a827b2a85839b16e9a56ad) есть такая необходимость:
WebDriver webDriver = new ChromeDriver(options);
var devConsoleCdpInterceptor = new DevConsoleCdpInterceptor(webDriver);
devConsoleCdpInterceptor.logFailedResponses();
решил сразу учесть такую возможность в юфите

2022-02-23 12:18 UTC, IovetsNikolay commented on src/main/java/com/loliktest/ufit/DevTools.java
> +    public static NetworkUfit network(org.openqa.selenium.devtools.DevTools devTools) {
Попробую порешать создание поля типа org.openqa.selenium.devtools.DevTools в классе DevTools

2022-02-23 12:20 UTC, IovetsNikolay commented on src/main/java/com/loliktest/ufit/chromeDevTools/FetchUfit.java
> +            FetchUfit.this.url = url;
Думал, но тут особенность именно не в построении нового а в частичной МОДИФИКАЦИИ того реквеста который мы перехватываем, думал вообще без билдера просто сетерами, но решил спрятать сетеры за недобилдером

2022-02-23 12:23 UTC, dbudim commented on src/main/java/com/loliktest/ufit/DevTools.java
> +    public static org.openqa.selenium.devtools.DevTools getCdpDevTools(WebDriver chromeDriver) {
не не, ufit это обертка, вебдрайвер - это ориджинал. То что я говорил тогда, в классе создания вэбдрайвера если возникает необходимость, то надо делать средствами селениума. 

Мы не можем использовать обертку над драйвером для того чтобы создать драйвер, который потом будет передаваться в обертку, это не очень правильно

2022-02-23 12:24 UTC, dbudim reviewed
не не, ufit это обертка, вебдрайвер - это ориджинал. То что я говорил тогда, в классе создания вэбдрайвера если возникает необходимость, то надо делать средствами селениума.

Мы не можем использовать обертку над драйвером для того чтобы создать драйвер, который потом будет передаваться в обертку, это не очень правильно

2022-02-23 12:29 UTC, IovetsNikolay commented on src/main/java/com/loliktest/ufit/chromeDevTools/NetworkUfit.java
> +    org.openqa.selenium.devtools.DevTools devTools;
fixed

2022-02-23 12:30 UTC, IovetsNikolay commented on src/main/java/com/loliktest/ufit/chromeDevTools/NetworkUfit.java
> +    void enableModifyFetch(List<RequestPattern> requestPattern) {
fixed

2022-02-23 12:49 UTC, IovetsNikolay commented on src/main/java/com/loliktest/ufit/chromeDevTools/NetworkUfit.java
> +        devTools.send(Fetch.disable());
Были мысли но само слово fetch не несет смысловой нагрузки, хз использовать его или нет в юфите. Я сомневаюсь, разнести типа не проблема

2022-02-23 12:54 UTC, IovetsNikolay commented on src/main/java/com/loliktest/ufit/chromeDevTools/NetworkUfit.java
> +    void enableModifyFetch(List<RequestPattern> requestPattern) {
Смысл в том чтобы enable методы вызывались только внутри пакеты в конкретных методах, а disable, которые нужно вызывать мануально, были public

2022-02-23 13:39 UTC, IovetsNikolay commented on src/main/java/com/loliktest/ufit/DevTools.java
> +    public static org.openqa.selenium.devtools.DevTools getCdpDevTools(WebDriver chromeDriver) {
оке пересмотрю логику

2022-04-26 08:38 UTC, closed without merging